[ace_world_patches]
repo = "ACEmulator/ACE-World-16PY-Patches"
tracked = "v0.9.292"
version_tag = true

[ace_world_base]
repo = "ACEmulator/ACE-World-16PY"
tracked = "v0.8.8"

[ace_pcap_exports]
repo = "ACEmulator/ACE-PCAP-Exports"
tracked = "v0.4.9"
