version: '3'
services:
  ace-db:
    image: mysql:latest
    container_name: ace-db
    env_file:
      - docker.env
    volumes:
      - ./scripts:/scripts
      - ./export:/var/lib/mysql-files
    ports:
      - "3306:3306/tcp"
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  ace-server:
    image: acemulator/ace:latest
    depends_on:
      - ace-db
    container_name: ace-server
    env_file:
      - docker.env
    ports:
      - "9000-9001:9000-9001/udp"
    restart: on-failure
