name: Publish latest databases
on:
  push:
    tags:
      - "latest"

jobs:
  export_ace_world_patches:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install datasette
        run: python3 -m pip install datasette
      - name: Install db-to-sqlite from my fork
        run: python3 -m pip install "db-to-sqlite @ git+https://github.com/amoeba/db-to-sqlite#egg=db-to-sqlite[mysql]"
      - name: Start MySQL
        run: sudo systemctl start mysql.service
      - name: Download release
        uses: robinraju/release-downloader@v1.12
        with:
          repository: ACEmulator/ACE-World-16PY-Patches
          latest: true
          fileName: "*.zip"
      - name: Decompress
        run: find . -iname "*.zip" -exec unzip {} \;
      - name: Load SQL
        run: sh scripts/load.sh
      - name: Export
        run: db-to-sqlite --all mysql://root:root@localhost/ace_world ace_world_patches.db
      - uses: actions/upload-artifact@v4
        with:
          name: ace_world_patches
          path: ./ace_world_patches.db
  export_ace_pcap_exports:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install datasette
        run: python3 -m pip install datasette
      - name: Install db-to-sqlite from my fork
        run: python3 -m pip install "db-to-sqlite @ git+https://github.com/amoeba/db-to-sqlite#egg=db-to-sqlite[mysql]"
      - name: Start MySQL
        run: sudo systemctl start mysql.service
      - name: Download latest release
        uses: robinraju/release-downloader@v1.12
        with:
          repository: ACEmulator/ACE-PCAP-Exports
          latest: true
          fileName: "*.zip"
      - name: Decompress
        run: find . -iname "*.zip" -exec unzip {} \;
      - name: Load SQL
        run: sh scripts/load.sh
      - name: Export
        run: db-to-sqlite --all mysql://root:root@localhost/ace_world ace_pcap_exports.db
      - uses: actions/upload-artifact@v4
        with:
          name: ace_pcap_exports
          path: ./ace_pcap_exports.db
  export_ace_base:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install datasette
        run: python3 -m pip install datasette
      - name: Install db-to-sqlite from my fork
        run: python3 -m pip install "db-to-sqlite @ git+https://github.com/amoeba/db-to-sqlite#egg=db-to-sqlite[mysql]"

      - name: Start MySQL
        run: sudo systemctl start mysql.service
      - name: Download release
        uses: robinraju/release-downloader@v1.12
        with:
          repository: ACEmulator/ACE-World-16PY
          latest: true
          fileName: "*.zip"
      - name: Decompress
        run: find . -iname "*.zip" -exec unzip {} \;
      - name: Load SQL
        run: sh scripts/load.sh
      - name: Export
        run: db-to-sqlite --all mysql://root:root@localhost/ace_world ace_world_base.db
      - uses: actions/upload-artifact@v4
        with:
          name: ace_world_base
          path: ./ace_world_base.db
  dogsheep:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python -m pip install github-to-sqlite
      - name: Create auth.json
        run: |
          echo "{\"github_personal_token\": \"${{ secrets.GITHUB_TOKEN }}\"}" > auth.json
      - run: github-to-sqlite issues github.db acemulator/ace
      - run: github-to-sqlite pull-requests github.db acemulator/ace
      - run: github-to-sqlite issue-comments github.db acemulator/ace
      - run: github-to-sqlite commits github.db acemulator/ace
      - run: github-to-sqlite contributors github.db acemulator/ace
      - uses: actions/upload-artifact@v4
        with:
          name: github.db
          path: ./github.db
  publish_latest_databases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      [
        export_ace_world_patches,
        export_ace_pcap_exports,
        export_ace_base,
        dogsheep,
      ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: "ace_world_patches"
      - uses: actions/download-artifact@v4
        with:
          name: "ace_pcap_exports"
      - uses: actions/download-artifact@v4
        with:
          name: "ace_world_base"
      - uses: actions/download-artifact@v4
        with:
          name: "github.db"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.db"
          allowUpdates: true
