name: Publish Release
on:
  push:
    tags:
      - "v*"
jobs:
  export_ace_world_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install datasette
        run: python3 -m pip install datasette
      - name: Install db-to-sqlite from my fork
        run: python3 -m pip install "db-to-sqlite @ git+https://github.com/amoeba/db-to-sqlite#egg=db-to-sqlite[mysql]"
      - name: Start MySQL
        run: sudo systemctl start mysql.service
      - name: Set pushed tag as an output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Download release
        uses: robinraju/release-downloader@v1.7
        with:
          repository: ACEmulator/ACE-World-16PY-Patches
          tag: ${{ steps.vars.outputs.tag }}
          fileName: *.zip
      - name: Decompress
        run: find . -iname "*.zip" -exec unzip {} \;
      - name: Load SQL
        run: sh scripts/load.sh
      - name: Export
        run: db-to-sqlite --all mysql://root:root@localhost/ace_world ace_world.db
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "ace_world.db"
